### ISSUE TITLE
attributes_to_store's deafult value is an empty array

### ISSUE THREAD

**Issue by szepeviktor** [michaeluno/admin-page-framework#242] opened 2016-02-19 17:22 UTC
May attributes_to_store have a must-have element, `id`?
That would solve #241 also.

**Comment by michaeluno** [comment] 2016-02-20 01:27
Are you having a problem storing attribute values associated with an attachment image? I remember `id` is not necessary. 

To check if the argument is functioning, 

1. Enable the Demo of the loader plugin 
2. Perform reset (Dashboard -> Demo -> Manage Options -> Reset).
3. Go to Dashboard -> Demo -> Built-in Field Types -> Files -> Save Image Attributes and pick an image and set some attribute values in the pop-up box. 
4. Go to Dashboard -> Demo -> Manage Options to see the values are saved properly. 

If the attributes are saved, check out the example code of that field (https://github.com/michaeluno/admin-page-framework/blob/3.7.11/example/admin_page/builtin_field_type/file/APF_Demo_BuiltinFieldTypes_File_Image.php#L89-L106). You may try removing the `id` element and see if the values get stored.

**Comment by szepeviktor** [comment] 2016-02-23 22:50
I think fixing #240 causes this problem.
I let you fix this as I don't understand certain function, parameters.

**Comment by michaeluno** [comment] 2016-07-27 00:33
Closing the topic as the problem is unclear.

**Closed by michaeluno** 2016-07-27 00:33 UTC
Labels: Unclear
