### ISSUE TITLE
Code field type

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#194] opened 2015-01-25 14:50 UTC
Hi,

I would like to request a "code" field type that will have a textarea similar to JSFiddle.

Is it possible any time soon?

Thanks,
Vlad.

**Comment by michaeluno** [comment] 2015-01-25 15:02
Hi,

I guess the [ace](https://github.com/soderlind/AceCustomFieldType) field type by Per Søderlind is what you are looking for. It is included in the demo component (Dashboard -> Demo -> Custom Field Types -> ACE ). 

You may want to check it out.

**Comment by vladkucherov** [comment] 2015-01-25 15:05
Hi,

Is there a chance to include it in the field types plugin / the main plugin?

**Comment by michaeluno** [comment] 2015-01-25 15:15
Not likely to be built-in. 

To register a custom field type, you just instantiate the class that defines the custom field type. It should be straight forward. 

Let me know if you have any difficulty doing that.

**Comment by vladkucherov** [comment] 2015-01-25 15:22
No difficulties, but it could be much easier if I didn't have to declare this:
```php
new AceCustomFieldType( __CLASS__ );
```
in every metabox I create. also I think we should have a method to set global options (like all the field by default should be HTML and not CSS)

**Comment by michaeluno** [comment] 2015-01-25 15:29
> but it could be much easier if I didn't have to declare this:

As of v3.5, it is no longer required. Try not passing anything. It is still recommended to set a class though because if a class name is not set, the field type will be site-wide which can cause unexpected behavior for other plugins that uses the framework.

**Comment by vladkucherov** [comment] 2015-01-25 17:19
It doesn't work without declaring a class.
the deceleration only works on demo mode (the file is not included)

is there away to initiate the class without including the file on demo off?

**Comment by michaeluno** [comment] 2015-01-26 03:39
> It doesn't work without declaring a class.

Have you tried this?

`
new AceCustomFieldType;
`
And comment out the other lines that instantiate it by passing the class name. This way, the field type will be registered site-wide not per a class basis.

**Comment by vladkucherov** [comment] 2015-01-26 07:13
Yes I figured this out already.
The problem is including the file... like with the rest of the files, I don't want to "know" the path to the file. especially if it's located inside "example"

maybe you should move the field type into the loader?

**Comment by michaeluno** [comment] 2015-01-26 08:24
Just copy the class that defines the field type into your plugin/theme and include it from your convenient location. I don't see why this is hard.

**Comment by vladkucherov** [comment] 2015-01-26 08:35
I am not saying it's hard, but I think everything related to the framework should be loaded by the framework.
I am just trying to come up with a better solution :-) that's all

**Comment by michaeluno** [comment] 2015-01-26 08:45
Maybe do you want an admin page that lists activated field types and lets you activate/deactivate/upload field types?

**Comment by vladkucherov** [comment] 2015-01-26 09:04
Like an add-on to the minifier?

**Comment by michaeluno** [comment] 2015-01-26 09:25
Like the plugins.php page of WordPress except that plugins are field types.

**Comment by vladkucherov** [comment] 2015-01-26 09:35
This is of course a great idea :+1:

**Comment by michaeluno** [comment] 2015-01-26 09:48
Can you post a new topic about it? I'm going to close this one as it seem to be resolved.

**Closed by michaeluno** 2015-01-26 09:48 UTC
