### ISSUE TITLE
Grammar error and 502 Bad Gateway

### ISSUE THREAD

**Issue by ivandotv** [michaeluno/admin-page-framework#226] opened 2015-11-17 21:09 UTC
![screenshot_00120151117 t](https://cloud.githubusercontent.com/assets/390700/11224893/878b6050-8d77-11e5-91ad-b13c4f072f5b.png)

Also, clicking on "Multiple Export Buttons" text gives "502 Bad Gateway"

**Comment by michaeluno** [comment] 2015-11-17 22:51
The typo of the button label will be fixed, thank you.

Regarding the 502 Bad Gateway error, I cannot reproduce it on my end. Can you try a clean install to see if the problem still occurs? Install a new WordPress test site only with the default theme and the Admin Page Framework loader plugin. Let me know how it goes.

**Comment by ikixxx** [comment] 2015-11-18 13:22
will do that , and report back. 
Btw, I'm using nginx.

**Comment by michaeluno** [comment] 2016-07-27 00:33
Closing the topic as the problem cannot be confirmed.

**Closed by michaeluno** 2016-07-27 00:33 UTC
Labels: Unconfirmed
